# Generated by Django 6.0.6 on 2026-07-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_add_logo_image_to_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True, help_text='Markdown supported')),
                ('status', models.CharField(choices=[('production', 'Production'), ('development', 'In Development'), ('research', 'Research'), ('archived', 'Archived')], default='production', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('cover_image', models.ImageField(blank=True, help_text='Large banner shown on the project detail page.', null=True, upload_to='projects/covers/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Small image shown on project cards and the homepage list.', null=True, upload_to='projects/thumbnails/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('case_study_url', models.URLField(blank=True)),
                ('metric_label', models.CharField(blank=True, max_length=60)),
                ('metric_value', models.CharField(blank=True, max_length=40)),
                ('categories', models.ManyToManyField(blank=True, help_text='Pick all that apply. Hold Ctrl/Cmd to select multiple.', related_name='projects', to='projects.category')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='core.techstack')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
