# Generated by Django 6.0.6 on 2026-06-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Large image shown at the top of the project detail page.', null=True, upload_to='projects/covers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='metric_label',
            field=models.CharField(blank=True, help_text='e.g. "Recovery rate"', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='metric_value',
            field=models.CharField(blank=True, help_text='e.g. "98.1%"', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Small image shown on project cards and the homepage list.', null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Pick all that apply. Hold Ctrl / Cmd to select multiple.', related_name='projects', to='projects.category'),
        ),
    ]
