# Generated by Django 6.0.6 on 2026-06-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_logo_image_to_siteconfig'),
        ('projects', '0004_technology_alter_project_technologies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.techstack'),
        ),
    ]
