# Generated by Django 6.0.6 on 2026-06-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Dev Mina', max_length=100)),
                ('tagline', models.CharField(default='Software Engineer & AI Systems Developer', max_length=200)),
                ('hero_headline', models.CharField(default='I build software that works.', max_length=300)),
                ('hero_subheadline', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True, help_text='Show "Open to opportunities" badge')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Languages'), ('framework', 'Frameworks'), ('database', 'Databases'), ('ai_ml', 'AI & Machine Learning'), ('automation', 'Automation'), ('tool', 'Tools & DevOps'), ('cloud', 'Cloud & Infrastructure')], max_length=30)),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class or SVG identifier', max_length=100)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Proficiency level 0–100 for visual bar')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
