# Generated by Django 6.0.6 on 2026-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='brand_name',
            field=models.CharField(default='MinaDXplorer', help_text='The logo wordmark shown in the nav and footer', max_length=60),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_headline',
            field=models.CharField(default='I build software that makes businesses smarter.', max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Show "Open to work" badge'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='proficiency',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
