# Generated by Django 6.0.6 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_copy_experience_certification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Your logo image. If blank the default SVG mark is used.', null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='brand_name',
            field=models.CharField(default='MinaDXplorer', help_text='Wordmark shown in nav and footer alongside the logo', max_length=60),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo shown in the About section.', null=True, upload_to='profile/'),
        ),
    ]
