# Generated by Django 6.0.6 on 2026-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('url', models.URLField()),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('twitter', 'X / Twitter'), ('youtube', 'YouTube'), ('podcast', 'Podcast'), ('other', 'Other')], default='linkedin', max_length=20)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
                'ordering': ['order', '-published_date'],
            },
        ),
    ]
